ci: add explicit GCC, LLVM build containers
Rename packages so that different variants have different names.
Previously, they had different versions.
Bump Qt to 6.6.1.
Bump docs container to keep version number consistent.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,59 +45,59 @@ jobs:
     needs: branch_info
     runs-on: ubuntu-latest
     steps:
-    # Conceptually, we only want to run this job iff we are a release.
-    # However, this greatly complicates that matrix build.
-    # Instead, exit succes on not release, and run my tag logic on release.
-    - name: No-op
-      if:  needs.branch_info.outputs.build_release != true
-      run: exit 0
-    - name: Check that release tag is well-formatted, and extract the version number
-      # Need explity == or the step triggers even if false
-      if: needs.branch_info.outputs.build_release == true
-      shell: bash
-      # Use xargs to trim spaces
-      run: |
-        tag=$(echo "${{ needs.branch_info.tag_name }}" | grep -Eo "v[0-9]+(\.[0-9]+)*$")
-        echo "VERSION_GIT=$(echo "${tag}" | cut -c3- | xargs)" >> $GITHUB_ENV
-    - name: Clone sources to extract project version
-      uses: actions/checkout@v4
-      if: needs.branch_info.outputs.build_release == true
-    - uses: lukka/get-cmake@v3.27.9
-      if: needs.branch_info.outputs.build_release == true
-    - name: Extract the CMake version
-      if: needs.branch_info.outputs.build_release == true
-      run: |
-        cmake -B build -S . -DONLY=VERSION
-        echo "VERSION_CMAKE=$(cat version | xargs)" >> $GITHUB_ENV
-    - name: CMake project version == Git tag
-      if: needs.branch_info.outputs.build_release == true
-      shell: bash
-      run: |
-        if [[ "$VERSION_CMAKE" != "$VERSION_GIT" ]] ; then
-          printf "Mismatched project versions. Git:$VERSION_GIT  CMake:$VERSION_CMAKE\n"
-          exit 115 # Use a sufficiently rare exit code to make this failure easy to detect
-        fi
+      # Conceptually, we only want to run this job iff we are a release.
+      # However, this greatly complicates that matrix build.
+      # Instead, exit succes on not release, and run my tag logic on release.
+      - name: No-op
+        if: needs.branch_info.outputs.build_release != true
+        run: exit 0
+      - name: Check that release tag is well-formatted, and extract the version number
+        # Need explity == or the step triggers even if false
+        if: needs.branch_info.outputs.build_release == true
+        shell: bash
+        # Use xargs to trim spaces
+        run: |
+          tag=$(echo "${{ needs.branch_info.tag_name }}" | grep -Eo "v[0-9]+(\.[0-9]+)*$")
+          echo "VERSION_GIT=$(echo "${tag}" | cut -c3- | xargs)" >> $GITHUB_ENV
+      - name: Clone sources to extract project version
+        uses: actions/checkout@v4
+        if: needs.branch_info.outputs.build_release == true
+      - uses: lukka/get-cmake@v3.27.9
+        if: needs.branch_info.outputs.build_release == true
+      - name: Extract the CMake version
+        if: needs.branch_info.outputs.build_release == true
+        run: |
+          cmake -B build -S . -DONLY=VERSION
+          echo "VERSION_CMAKE=$(cat version | xargs)" >> $GITHUB_ENV
+      - name: CMake project version == Git tag
+        if: needs.branch_info.outputs.build_release == true
+        shell: bash
+        run: |
+          if [[ "$VERSION_CMAKE" != "$VERSION_GIT" ]] ; then
+            printf "Mismatched project versions. Git:$VERSION_GIT  CMake:$VERSION_CMAKE\n"
+            exit 115 # Use a sufficiently rare exit code to make this failure easy to detect
+          fi
   build_docs:
     runs-on: ubuntu-latest
     container:
-      image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0-docs"
+      image: "ghcr.io/matthew-mcraven/pepp/docs:v0.10.0"
     steps:
-    # Must exectute before any repo-local actions
-    - uses: actions/checkout@v4
-    # Install dependencies based on enabled features
-    - if: env.ACT
-      uses: ./.github/actions/install-node
-    # No need to check out submodules, since we only build our own docs
-    - name: Configure cmake for docs
-      run: cmake -B build -S . -DONLY=DOC -DDOC_AUDIENCE=APP
-    - run: cmake --build build && ls build/docs
-    - uses: actions/upload-artifact@v4
-      with:
-        name: app-docs
-        path: build/docs
-        retention-days: 1
+      # Must exectute before any repo-local actions
+      - uses: actions/checkout@v4
+      # Install dependencies based on enabled features
+      - if: env.ACT
+        uses: ./.github/actions/install-node
+      # No need to check out submodules, since we only build our own docs
+      - name: Configure cmake for docs
+        run: cmake -B build -S . -DONLY=DOC -DDOC_AUDIENCE=APP
+      - run: cmake --build build && ls build/docs
+      - uses: actions/upload-artifact@v4
+        with:
+          name: app-docs
+          path: build/docs
+          retention-days: 1
   start_matrix:
-    needs: [branch_info, build_docs, check_tag]
+    needs: [ branch_info, build_docs, check_tag ]
     uses: ./.github/workflows/build.yml
     strategy:
       fail-fast: true
@@ -105,13 +105,13 @@ jobs:
       # Trying to use `env` or inputs will fail in this context.
       matrix:
         config:
-        - {name: "Ubuntu 22.04; GCC", cache_name: 'ubuntu-gcc', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0", compiler_launcher: "ccache", compiler_c: "", compiler_cpp: "", cmake_generator: "Ninja"}
-        # Do CodeQL in clang run, to prevent needing yet another target.
-        - {name: "Ubuntu 22.04; Clang 17.0", cache_name: 'ubuntu-clang', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0",  compiler_launcher: "", compiler_c: "clang", compiler_cpp: "clang++" , cmake_generator: "Ninja"}
-        - {name: "Ubuntu 22.04; EMSDK 3.1.37", cache_name: 'ubuntu-emsdk', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev:v0.9.0-wasm", cmake_toolchain: '$Qt6_DIR/qt.toolchain.cmake', cmake_xargs: '-D QT_HOST_PATH=/qt/6.6.0/gcc_64', docs_audience: 'WEB', release_type: 'MinSizeRel'}
-        # See: https://bugreports.qt.io/browse/QTBUG-118086
-        - {name: "MacOS-14; Clang 15.0.7", cache_name: 'macos-clang', runs-on: "macos-14" , compiler_launcher: "ccache", compiler_c: '$(brew --prefix llvm@15)/bin/clang', compiler_cpp: '$(brew --prefix llvm@15)/bin/clang++', cmake_generator: "Ninja"}
-        - {name: "Windows Latest; MSVC", cache_name: 'windows-msvc', runs-on: "windows-latest" , compiler_launcher: "ccache",}
+          - { name: "Ubuntu 22.04; GCC", cache_name: 'ubuntu-gcc', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev-gcc:v0.10.0", compiler_launcher: "ccache", compiler_c: "", compiler_cpp: "", cmake_generator: "Ninja" }
+          # Do CodeQL in clang run, to prevent needing yet another target.
+          - { name: "Ubuntu 22.04; Clang 17.0", cache_name: 'ubuntu-clang', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev-clang:v0.10.0",  compiler_launcher: "", compiler_c: "clang", compiler_cpp: "clang++" , cmake_generator: "Ninja" }
+          - { name: "Ubuntu 22.04; EMSDK 3.1.37", cache_name: 'ubuntu-emsdk', runs-on: "ubuntu-latest", image: "ghcr.io/matthew-mcraven/pepp/dev-wasm:v0.10.0", cmake_toolchain: '$Qt6_DIR/qt.toolchain.cmake', cmake_xargs: '-D QT_HOST_PATH=/qt/6.6.1/gcc_64', docs_audience: 'WEB', release_type: 'MinSizeRel' }
+          # See: https://bugreports.qt.io/browse/QTBUG-118086
+          - { name: "MacOS-14; Clang 15.0.7", cache_name: 'macos-clang', runs-on: "macos-14" , compiler_launcher: "ccache", compiler_c: '$(brew --prefix llvm@15)/bin/clang', compiler_cpp: '$(brew --prefix llvm@15)/bin/clang++', cmake_generator: "Ninja" }
+          - { name: "Windows Latest; MSVC", cache_name: 'windows-msvc', runs-on: "windows-latest" , compiler_launcher: "ccache", }
     with:
       name: ${{ matrix.config.name }}
       cache_name: ${{ matrix.config.cache_name }}
